POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "email": "peter@mail.ru",
  "password": "Qwerty"
}

###


POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "email": "darja@mail.ru",
  "password": "qWerty"
}

###

POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
  "email": "ivan@mail.ru",
  "password": "qwErty"
}

###
