name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        env:
          HOME: '/Lesson_26'
        run: docker build -t {{ secrets.DOCKER_USER }}/{{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u {{ secrets.DOCKER_USER }} --password-stdin
      - name: docker push
        run: docker push {{ secrets.DOCKER_USER }}/{{ secrets.REPO_NAME }}:$GITHUB_REF_NAME-GITHUB_RUN_ID